### PR TITLE
Convenience changes.

### PR DESCRIPTION
**Pull request by soverysour**
All the commit messages should be explanatory enough:

1. Added bin/ to .gitignore, just because I used bin/ instead of build/ ( same thing)
    Also, added fade_out_music() when going for a new game at the postmortem screen, so Musica Cthulhiana - Madness didn't overlap with the actual game.
2. Changed case from lower to upper in the popup window for 'yes' and 'no'.
3. Made it so that when you press ESC in the character creation set of screens, in the background, trait and name ones, you go back to the main menu. Pressing ESC in the "Initial Story" window works like before - it closes it so you can start to actually play.

### CODE REVIEW

**Comment by martin-tornqvist** [comment]
Thanks for the contribution!

> 1. Added bin/ to .gitignore, just because I used bin/ instead of build/ ( same thing)
>     Also, added fade_out_music() when going for a new game at the postmortem screen, so Musica Cthulhiana - Madness didn't overlap with the actual game.

Good catch about fading out the music - thanks!

> 2. Changed case from lower to upper in the popup window for 'yes' and 'no'.

Yeah I guess that looks better.

> 3. Made it so that when you press ESC in the character creation set of screens, in the background, trait and name ones, you go back to the main menu. Pressing ESC in the "Initial Story" window works like before - it closes it so you can start to actually play.

The intention of this is good. However I don't like the implementation that a specific number of states are popped. It seems fragile and hard to maintain. However, it's probably hard to do anything nicer as things are now.

What I think should be done, is that each state has a type id (an enum class value), and that the state handler has something like

`pop_states_until(const StateId state_id)`

Then you could very conveniently tear down all states until for example the main menu state, or until the game state.

I will pick your other two commits, but this one I'm gonna have to look at a different implementation for.

**Comment by soverysour** [comment]
> It seems fragile and hard to maintain.

Yeah, I thought about that too. However, I looked in some other function from that file, something similar to a constructor, and in that one you pushed, in reverse order of the appearance, four states, and I decided to pop based on that.

Thinking about it, I think the way you suggested things be done is the best - I was thinking about something similar, but much more tedious.

I would like to redo that bit myself, but I'll have to get more familiar with the code-base. Nonetheless, it's going to be !fun!; that and any further contributions.

**Comment by martin-tornqvist** [comment]
> However, I looked in some other function from that file, something similar to a constructor, and in that one you pushed, in reverse order of the appearance, four states, and I decided to pop based on that.

Yeah your code probably works fine for now, it's just a maintainability issue.

> I would like to redo that bit myself

Alright, cool.

I suggest a pure virtual method on the state base class:

`StateId id() const = 0;`

Where StateId would be an enum class declared in state.hpp.

Hm, could you do another pull request for the two other commits? I think that would be the best way to merge them in.

**Comment by soverysour** [comment]
About making a PR just for those two commits, I don't know how I'd do that, but you can [cherry pick](https://mattstauffer.co/blog/how-to-merge-only-specific-commits-from-a-pull-request) it. 

I hope that works.

(You could, though, just merge it all. The maintainability issue will become important only in the distant future, IMO, and it will have already been reimplemented by that point.)

**Comment by martin-tornqvist** [comment]
I cherry picked bbe2565c5c305c17251d8dccc126220f803d3a29 and 31b98ecbfe6276b91ed785ec8cd86d3f3292fd4e now.

There is actually another issue with a558588f79add2a3c6bf7dbec81154b1388716fe. Pressing escape while in the trait selection screen due to gaining a new character level would cause a lot of trouble. This screen needs different handling depending on how you got there.

The trait selection screen must consider whether the player is creating a new character or has gained a new character level.

One possible way to do this is if the trait state checks if there is a "name state" (player entering name) in the stack or not (via a new function in the state namespace, e.g. `bool is_state_in_stack(const StateId state_id)`). If there is such a state, it means we are creating a new character. It's a bit of a hack - but it would work.

Another way could be to provide a enum class parameter in the trait state constructor, and store it as a member variable of the trait state class, something like:

`
enum class TraitSelectSource {new_game, gained_level};
`

(Probably a better solution)

I'm closing this pull request now.

**Pull request closed without merging**
