### PR TITLE
A possible fix to issue #86

### LINKED ISSUE #86: Different message when bumping walls compared to hidden doors
**"The way is blocked."** (default) vs **"That way is blocked."** (doors).

This unintentionally allows players to detect hidden doors simply by bumping walls.

In feature_door.cpp a custom message is printed (the second one). The solution is probably to read the message string from the feature data, and print that instead.

### PR DESCRIPTION
**Pull request by ethanfine**
fixes #86

### CODE REVIEW

**Comment by martin-tornqvist** [comment]
I agree that the door should read the messages from the wall data. But I don't agree with checking with the property handler if player can see. It should check if the the player sees the door cell, as it did before. Although today it's probably effectively the same, but who knows in the future, maybe there's some psychic ability to let you see while blinded? ;-).

**Comment by ethanfine** [comment]
I changed that to match how it is done in feature.cpp so that the secret door and wall would be entirely indistinguishable. It should either be changed in Feature to how it was in Door, or changed in Door to how it is in Feature. Anything else leaves the possibility of distinguishing a hidden door from a wall.

If you want I could change them both to how it was done in Door?

**Comment by martin-tornqvist** [comment]
Okay I see. Yeah I think it's best to do it like it was done for the Door,
in both cases. If you can see the cell or not should be what actually
matters.

**Comment by ethanfine** [comment]
How's that?

**Comment by martin-tornqvist** [comment]
Looks good, thanks again!

**Pull request merged**
