### PR TITLE
Aspect ratio and pixel sharpness now preserved in full-screen

### PR DESCRIPTION
**Pull request by laleksic**
Hello Martin,

I'm submitting a patch that fixes the stretching and distorsion in full-screen. Best illustrated by before/after screenshots -- https://imgur.com/a/TDb2t

### CODE REVIEW

**Comment by martin-tornqvist** [comment]
This severely messed up my screen when I switched to fullscreen though:

https://ibb.co/igV6Mn

**Comment by laleksic** [comment]
I think it may be due to driver trouble...

While testing this code on my desktop, something similar happened (though not as extreme) but it was before I installed propriatery NVidia drivers for my GPU. That fixed it permanently.

I'm running Linux, Fedora 27 Xfce, and that effect only happened with Linux's default open source drivers for NVidia GPUs.

I've also tested it on my laptop, which has Intel integrated GPU, and it works as it should with the default drivers.

The point is, it may have something to do with the hardware accelerated SDL renderer. Maybe forcing software renderer would fix it (I saw in the code that the hardware renderer is on by default)? Does Infra Arcana even need hardware accelerated graphics?

**Comment by martin-tornqvist** [comment]
>Does Infra Arcana even need hardware accelerated graphics?

I tried it with software rendering instead (creating the sdl renderer with SDL_RENDERER_SOFTWARE the first time, and removing the whole if-scope below which set up a sw renderer in case the hw one failed) - that seems to have fixed the issue!

No I guess there's actually no reason to use hw accelerated rending.

Do you think you could update the pull req with the change above? And also, use spaces instead of tabs. Then I'll merge it.

P.S. Thanks for the contribution and idea :)

**Comment by laleksic** [comment]
Done. You're welcome :)! Thank you for IA.

**Comment by martin-tornqvist** [comment]
>On big screens such as yours, a lot of the screen will go unused
It could still be nice to run fullscreen though, to get more immersed in the game.

One thing I should mention is that I'm currently working on redesigning the gui, and having differently sized maps with a scrolling viewport. This affects fullscreen, since the game should just show as many map cells as possible, without any stretching. I think your change will be the correct way to render when this is done.

**Comment by laleksic** [comment]
I see. You're right in that case.

**Comment by aeoo** [comment]
However, it would then be nice to be able to double the size of every tile, because the entire reason I was using fullscreen before this change is to make everything more visible.  Immersion wasn't all that relevant to me.  I just wanted to be able to see the details easier by making them bigger.  Now I cannot do that anymore.

**Comment by martin-tornqvist** [comment]
Maybe adding a setting to scale the graphics and font to double size would
be a good solution.

**Pull request merged**
